# Generated by Django 4.0 on 2022-01-02 10:06

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format:required, max = 255', max_length=255, verbose_name='category name')),
                ('slug', models.SlugField(max_length=255, verbose_name='safe URL')),
                ('is_active', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child', to='Inventory.category', verbose_name='parent of category')),
            ],
            options={
                'verbose_name': 'Product cateogry',
                'verbose_name_plural': 'product_categories',
            },
        ),
    ]
